[package]
name = "cartridge_vrf"
version = "0.1.0"
edition = "2023_10"

[dependencies]
starknet = "2.11.4"
stark_vrf = { git = "https://github.com/dojoengine/stark-vrf.git" }
openzeppelin_access = "2.0.0"
openzeppelin_upgrades = "2.0.0"
snforge_std = "0.38.3"

[dev-dependencies]
openzeppelin_testing = "2.0.0"
openzeppelin_utils = "2.0.0"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"

[lib]

[script]
test = "snforge test"
